### ISSUE TITLE
Router issues

### ISSUE THREAD

**Issue by steven9255** [cryptoguy55a/shininggowl-reddit-clone-frontend#1]
Hello. How are you?
I am learning react and golang from your repository
but I have one issue with React Router
I am following you from scketch
But your code have issue on router part
Please help me
Thank you. steven

**Comment by stackcraft55** [comment]
Hello. Steven
I think you installed the react router v6
v6 is different with v5
Please check my package.json file
Also I'd like to read the articles about difference of two versions
https://dev.to/arunavamodak/react-router-v5-vs-v6-dp0
Thank you.

**Comment by steven9255** [comment]
Thank you.,
